// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMNMWPS2m_Ls3ma-LYMjmAoSk-KLQxICw',
    appId: '1:91517816937:web:33079acdde330d928692f8',
    messagingSenderId: '91517816937',
    projectId: 'qwikhom-79b47',
    authDomain: 'qwikhom-79b47.firebaseapp.com',
    storageBucket: 'qwikhom-79b47.firebasestorage.app',
    measurementId: 'G-1DV0YXEZN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbi9B_uys5hOiqxFKDOCDZn1lJp3PFbQ0',
    appId: '1:91517816937:android:afb073ee0d59acea8692f8',
    messagingSenderId: '91517816937',
    projectId: 'qwikhom-79b47',
    storageBucket: 'qwikhom-79b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAvi48czTsxyGB5wSTswnIckaYxVC59So',
    appId: '1:91517816937:ios:b031312346f79e288692f8',
    messagingSenderId: '91517816937',
    projectId: 'qwikhom-79b47',
    storageBucket: 'qwikhom-79b47.firebasestorage.app',
    iosBundleId: 'com.example.quickHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAvi48czTsxyGB5wSTswnIckaYxVC59So',
    appId: '1:91517816937:ios:b031312346f79e288692f8',
    messagingSenderId: '91517816937',
    projectId: 'qwikhom-79b47',
    storageBucket: 'qwikhom-79b47.firebasestorage.app',
    iosBundleId: 'com.example.quickHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMNMWPS2m_Ls3ma-LYMjmAoSk-KLQxICw',
    appId: '1:91517816937:web:c513736a4cd5603c8692f8',
    messagingSenderId: '91517816937',
    projectId: 'qwikhom-79b47',
    authDomain: 'qwikhom-79b47.firebaseapp.com',
    storageBucket: 'qwikhom-79b47.firebasestorage.app',
    measurementId: 'G-9KL9WDNW44',
  );
}
